apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-server
  namespace: litmus
  labels:
    component: litmusportal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: litmusportal-server
  template:
    metadata:
      labels:
        component: litmusportal-server
    spec:
      containers:
      - name: graphql-server
        image: litmuschaos/litmusportal-server:ci
        env:
          - name: DB_SERVER
            value: mongo-service:27017
          - name: CLUSTER_JWT_SECRET
            value: "12345678"
          - name: EXTERNAL_ADDRESS
            value: ""
          - name: SERVICE_ADDRESS
            value: litmusportal-server-service:8080
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      - name: auth-server
        image: litmuschaos/litmusportal-auth-server:ci
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
